### ISSUE TITLE
A rule is needed

### ISSUE THREAD

**Issue by ayehninnkhine** [greenlikeorange/knayi-myscript#17]
Change \u1025\u102E to \u 1026.
ဥ နဲ့ ီ ကို ဦ လို့ပြန်ပြောင်းပေးဖို့ကျန်ခဲ့တာလေးတွေ့လို့ပါ။

**Comment by kaungmyatlwin** [comment]
Reproduction steps sis?

**Comment by ayehninnkhine** [comment]
Just to replace [\u1925\u102E] to \u1026, bro.

**Comment by greenlikeorange** [comment]
Sorry, which step you mean @ayehninnkhine converting uni -> zaw or zaw -> uni.

**Comment by ayehninnkhine** [comment]
Ah, sorry for my incomplete info. At the stage of converting zawgyi->unicode bro.

**Comment by greenlikeorange** [comment]
Check your library version please and update to 2.x
If your using < 2, I currently don't have plan to release patch for 1.x
Thank
