### ISSUE TITLE
Looking help for update detection script by using googlei18n/myanmar-tool

### ISSUE THREAD

**Issue by greenlikeorange** [greenlikeorange/knayi-myscript#18]
I was looking for help to add https://github.com/googlei18n/myanmar-tools to knayi-myscript library.

**Comment by kaungmyatlwin** [comment]
Will `detector.js` be obsolete if `myanmar-tools` is added?

**Comment by greenlikeorange** [comment]
I saw more promising at `myanmar-tools`,want to add it as a dependence of `detector.js`. So no method names will change, the library have same API, but more accurate.

**Comment by greenlikeorange** [comment]
@kaungmyatlwin Thank for interest on this issue, but I found some interesting things to look along with pull request #20. If we add the whole **myanmar-tool** in build, knayi will be a lot bigger. I don't think it is good for client side as a default.

I was thinking about giving an option of using **myanmar-tool** OR not. As google host script on it own cdn, we can append `<script>` tag on *client side* when developer choose `myanmar-tool` option.
But for server side, we can do **myanmar-tool** as `dependencie` in `package.json`

**Example init script**
```html
<body>
  <script src="dist/knayi-myscript.min.js"></script>
  <script>
  // .config function is option, so no API breaking change for old app
  // Default use_myanmar_tool_for_detection is false
  knayi.config({use_myanmar_tool_for_detection: true})
  // Then knayi will add "myanmar-tool"
  //....
  </script>
```

Note: Further discussing may need

**Comment by kaungmyatlwin** [comment]
What you're stating about appending `script` to HTML might be a bit overkill. If you look at your current `dist` files, almost all of them have approx `9kb` file. I've tested building with `myanmar-tool` included, and it's surprisingly very small so it will only take a few bytes which isn't a problem even for client-side.

It's still a good thought to add config whether to use the dependency.
