### ISSUE TITLE
New Version

### ISSUE THREAD

**Issue by greenlikeorange** [greenlikeorange/knayi-myscript#5]
The new version is more focus on language typography, more ethic languages and web-screen keyboard.

**Comment by mapmeld** [comment]
I tried updating knayi-cli to 1.0.10, but now the async version of fontConvert is not working.

When from = null, ```function fontConvert( content, to, from )``` does not detect the "from" font

**Comment by greenlikeorange** [comment]
@mapmeld Thank for report, I fixed that on 1.0.11.
Check it out.
